# Generated by Django 2.1.7 on 2019-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='date_purchased',
            field=models.DateTimeField(default=1),
        ),
    ]
