# Generated by Django 2.1.7 on 2019-02-16 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190216_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='avatar2',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/product'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 16, 10, 34, 25, 23246)),
        ),
    ]
