# Generated by Django 2.1.7 on 2019-02-16 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_auto_20190216_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, default='DA', max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchTerm',
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 16, 11, 7, 37, 878729)),
        ),
    ]
