# Generated by Django 2.1.7 on 2019-02-16 11:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190216_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='categories_active',
            field=models.ManyToManyField(blank=True, null=True, related_name='brands', to='home.Category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, related_name='brands', to='home.Customer'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_friends', to='home.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='home.Product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ineterests',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_interests', to='home.Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_wishlist', to='home.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='home.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dicount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='home.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date', to='home.Customer'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 16, 11, 14, 25, 908063)),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date', to='home.Product'),
        ),
    ]
